version: '3'
services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: 1q2w3e4r5t6y
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/budget
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1q2w3e4r5t6y
    restart: always
    links:
      - db
